# Generated by Django 3.1.1 on 2024-07-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordreplacement',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='keywordreplacement',
            name='replacement',
        ),
        migrations.CreateModel(
            name='KeywordReplacementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('replacement', models.CharField(max_length=255)),
                ('keyword_replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot.keywordreplacement')),
            ],
        ),
    ]
